vich_uploader:
    db_driver: orm

    mappings:
        postPicture:
            uri_prefix: /images/picture
            upload_destination: '%kernel.project_dir%/public/images/picture'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        userAvatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
